### ISSUE TITLE
    assert 0.0 > split < 1.0  AssertionError

### ISSUE THREAD

**Issue by pandaxue** [metal3d/keras-video-generators#1]
I don’t quite understand what you mean, I haven’t changed any code except the path of the video file, split=0.2 I added, but there is still an error in the picture,
![123](https://user-images.githubusercontent.com/50400428/70135888-e421a500-16c5-11ea-90b6-94eb87186f59.png)

**Comment by pandaxue** [comment]
I've been using Python3, I haven't used Python2, but there will still be errors like this,

**Comment by metal3d** [comment]
Ok, the problem is that the "assertion" is not reconized. Can you please try to copy/paste that code in a new script, and give me the result:

```python
import sys
print(sys.__version__)
a = 5
assert 1 > a < 10
```

**Comment by pandaxue** [comment]
![image](https://user-images.githubusercontent.com/50400428/70136440-f6e8a980-16c6-11ea-8d3b-9c1d85427664.png)

**Comment by metal3d** [comment]
sorry, change `__version__` with `version`: `sys.version`

**Comment by metal3d** [comment]
ok, I see the problem... I inverted assertion

**Comment by pandaxue** [comment]
![image](https://user-images.githubusercontent.com/50400428/70136686-74acb500-16c7-11ea-8c5f-fee2026ab773.png)

**Comment by metal3d** [comment]
I fixed the issue, please consider to upgrade the package with `pip install --upgrade keras-video-generators` (that is now version 1.0.4) and recheck.

**Comment by pandaxue** [comment]
ok, thank you! very nice

**Comment by metal3d** [comment]
No problem, when it's ok, tell me, so I can close that issue

**Comment by pandaxue** [comment]
now it is ok, thank you again!

**Comment by metal3d** [comment]
Thanks for that issue, it's a pleasure to help :)
