### ISSUE TITLE
Question regarding predictions

### ISSUE THREAD

**Issue by ZumelzuR** [metal3d/keras-video-generators#24]
Hello!!! I have a question, is it possible to use the transformations in order to perform the predictions over the trained model? I mean, the model was trained in (batch_size ,nbframes, img_size, img_size, channels),  and the input video was represented for an array of transformations of nbframes, so when I want to perform predictions over videos that are not in the dataset, I think that I need to use same transformations and get some representatives frames as you do on the library. So there are any way to do this with the library ? thanks!

**Comment by ZumelzuR** [comment]
Sorry again, I solved but I just implement a function for transform the image like

`def cv_transform(img):
     img = cv2.resize(img, SIZE)
     img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
     img = img_to_array(img) * 1/255.
     return img
`

maybe I can put on the library but the transformation for the predictions will depends of the model (channel, size, etc)

**Comment by metal3d** [comment]
I'm really sorry but I don't understand what you need.

If you want perform transformations on data to predict, you can:
- create another VideoFrameGenerator (or other) with transformation function passed as parameter  on a different directory (glob_pattern)
- simply open video, pick frames, and make transformation
