### ISSUE TITLE
'VideoFrameGenerator' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Raman1121** [metal3d/keras-video-generators#29]
I am getting the following error while using .fit_generator method: 
AttributeError: 'VideoFrameGenerator' object has no attribute 'shape'.
![image](https://user-images.githubusercontent.com/21155059/83384141-4143ac80-a404-11ea-8736-57aba60b2d35.png)

**Comment by metal3d** [comment]
Hi, 
Can you confirm the version you are using and tell me if you're using keras or tensorflow.keras ?
