### ISSUE TITLE
Will this work for long sequence?

### ISSUE THREAD

**Issue by kinjalmistree** [metal3d/keras-video-generators#35]
Hi, it's really good explanation that you have provided in slideframegenerator.py.
I have just 1 question, may this work for long sequences in a video? I am working with hand gesture recognition.

**Comment by metal3d** [comment]
We also use it for gesture recognition, what do you call "long sequence" ?

**Comment by kinjalmistree** [comment]
I mean long sequence means, in a sequence multiple gestures are there. Like one gesture is followed by 4-5 other gestures. Basically, each video (of 30 FPS) has length of 7-8 seconds. 
Also, we can have cases like gesture overlapping, means one gesture may occur in multiple seqeunces.

**Comment by metal3d** [comment]
This generator is made to train model, and as for common neural network, your input is managed by your neural network. Keras-Videos-generator is specially built to split videos in sequences of several frames, the number of sequences and frames is a finite number.
To manage long sequences, you need to get the stream, split parts, and send them as batches. This is a long work that is not related to the generator.
We (at Smile Opensource Solution) are working on this (project https://koda-inc.fr/) to collect videos and try to build a solution. But that's a research project that uses this generator to train models (among other experimentations).

Regards,
