### ISSUE TITLE
ModuleNotFoundError: No module named 'keras_video'

### ISSUE THREAD

**Issue by dalekube** [metal3d/keras-video-generators#4]
Documentation suggests the module can be loaded using the 'keras_video' alias. However, this name is not linked to the 'keras-video-generators' package (version 1.0.4) that I installed using pip. I am receiving the 'ModuleNotFoundError' message.

Ubuntu 19.10
Python 3.7.5
keras-video-generators 1.0.4

**Comment by 27KEERTHANA** [comment]
I am also having the same problem. I got successfully installed the keras-video-generators package but receiving ModuleNotFoundError.
![Capture](https://user-images.githubusercontent.com/49174676/71675744-71394600-2db9-11ea-9830-7ee3aff77873.JPG)

**Comment by metal3d** [comment]
Thanks a lot, I found the problem and I will push the fix + new version in a couple of minutes. Sorry for that !

**Comment by metal3d** [comment]
See https://pypi.org/project/keras-video-generators/, version 1.0.5 fixed, can you test and tell me if it's ok ?

**Comment by dalekube** [comment]
Looks good! I am now able to properly import the module with 'import keras_video'.
