### ISSUE TITLE
Add a `set seed` feature to split?

### ISSUE THREAD

**Issue by YueWangpl** [metal3d/keras-video-generators#43]
It's not a bug so I'll ignore the template. I think allowing a user-defined set.seed/ random state would really be helpful since we'd like to replicate our results. And more importantly, if training two models in separate notebooks/machines and ensemble them, it becomes a disaster since all data are probably seen by them jointly.

**Comment by metal3d** [comment]
Right ! nice idea !

**Comment by metal3d** [comment]
Done in commit cde4d030
